### ISSUE TITLE
No icon in VSCode.

### ISSUE THREAD

**Issue by philippevidal80** [4ops/vscode-language-packer#1]
Hello,

I'm using you plugin but icon in Explorer stay as a default text icon although highlighting and syntaxt correction for Packer is working well.
![packer_vsc](https://user-images.githubusercontent.com/10353107/88896852-b851c180-d24a-11ea-869d-e5ff1438a83f.png)

**Comment by philippevidal80** [comment]
Maybe it's because of the size of the icon. In master it is 599x599 pxl but icon must be of the size 128x128 apparently.
I join an icon of 128x128 in case it is useful.
![icon](https://user-images.githubusercontent.com/10353107/88897633-e7b4fe00-d24b-11ea-908a-55e5342e2173.png)

**Comment by 4ops** [comment]
Hi, @philippevidal80 
My extension contains the icon that showed in marketplace only. If you want to change file icons, you must install [icon theme](https://code.visualstudio.com/blogs/2016/09/08/icon-themes).
