### ISSUE TITLE
Support .pkrvars.hcl files

### ISSUE THREAD

**Issue by emyl** [4ops/vscode-language-packer#2]
Hi,

As per [Packer docs](https://www.packer.io/docs/from-1.5/variables), variable definition files should have `.pkrvars.hcl` extension. It would be great if syntax highlighting could also include those files.

Thanks!

**Comment by 4ops** [comment]
I'm sorry, don't have a lot of time. I do it ASAP

**Comment by 4ops** [comment]
Added in release [0.2.0](https://github.com/4ops/vscode-language-packer/blob/master/CHANGELOG.md#020)
